### ISSUE TITLE
Local variable 'firstVarLine' referenced before assignment. (Solution proposal inside)

### ISSUE THREAD

**Issue by Carbaz** [Feneric/doxypypy#38]
I got the following exception while running on doxywizard: (I truncated it to the relevant point)

```
Traceback (most recent call last): 
  ...
  File "/usr/local/lib/python2.7/dist-packages/doxypypy/doxypypy.py", line 470, in _processDocstring
    if '@property\t' in firstVarLine:
UnboundLocalError: local variable 'firstVarLine' referenced before assignment
```

I found looking to your code on the repository that in line 471 yo checks over the firstVarLine variable which may have not been assigned if the previous for loop iterates 0 times.

Maybe extending that _if_ condition with _(lastVarLineNum > 0)_ would the problem be solved.
(Not checked the full logic, just an "on the fly" idea)
`if lastVarLineNum > 0 and '@property\t' in firstVarLine:`

**Comment by Feneric** [comment]
Good catch. I'll take a look.

**Comment by JiriValasek** [comment]
Hi, I got the same exception while running doxywizard:

`
Reading C:/Program Files/FreeCAD 0.18/Mod/Animate/InitGui.py...
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\lib\site-packages\doxypypy\doxypypy.py", line 836, in 
    main()
  File "C:\Program Files\Python36\lib\site-packages\doxypypy\doxypypy.py", line 830, in main
    astWalker.parseLines()
  File "C:\Program Files\Python36\lib\site-packages\doxypypy\doxypypy.py", line 743, in parseLines
    self.visit(inAst)
  File "C:\Program Files\Python36\lib\site-packages\doxypypy\doxypypy.py", line 569, in visit
    return visitor(node, containingNodes=containingNodes)
  File "C:\Program Files\Python36\lib\site-packages\doxypypy\doxypypy.py", line 595, in visit_Module
    []))
  File "C:\Program Files\Python36\lib\site-packages\doxypypy\doxypypy.py", line 553, in generic_visit
    self.visit(item, containingNodes=kwargs['containingNodes'])
  File "C:\Program Files\Python36\lib\site-packages\doxypypy\doxypypy.py", line 569, in visit
    return visitor(node, containingNodes=containingNodes)
  File "C:\Program Files\Python36\lib\site-packages\doxypypy\doxypypy.py", line 733, in visit_ClassDef
    containingNodes=containingNodes)
  File "C:\Program Files\Python36\lib\site-packages\doxypypy\doxypypy.py", line 470, in _processDocstring
    if '@property\t' in firstVarLine:
UnboundLocalError: local variable 'firstVarLine' referenced before assignment`

Was the issue somehow resolved?

**Comment by vocx-fc** [comment]
Hi, has anything been done about this? It seems this bug has been open for a while. I want to use doxypypy to process the documentation of [FreeCAD](https://github.com/FreeCAD/FreeCAD/tree/master/src/Mod/Draft). Some Python code is badly formatted and that seems to cause errors with doxypypy; it's ultimately FreeCAD's fault, although it would be nice if doxypypy didn't error out.

In particular a bad docstring seems to cause this error, like
```
class DraftWorkbench (Workbench):
    #the Draft Workbench
    def __init__(self):
```

**Comment by Feneric** [comment]
I remember starting to look into this but then I got sidetracked and didn't get back to it. If I'm lucky I may have a chance to look into it this weekend.
