### ISSUE TITLE
NodeVisitor:visit_Constant() argument containingNodes unexpected keyword (python 3.8)

### ISSUE THREAD

**Issue by svigerske** [Feneric/doxypypy#70]
I did an update to Python 3.8.1 and cannot run doxypypy anymore.
With the current master, I get:
```
$ ./doxypypy.py doxypypy.py 
Traceback (most recent call last):
  File "./doxypypy.py", line 901, in <module>
    main()
  File "./doxypypy.py", line 890, in main
    astWalker.parseLines()
  File "./doxypypy.py", line 772, in parseLines
    self.visit(inAst)
  File "./doxypypy.py", line 582, in visit
    return visitor(node, containingNodes=containingNodes)
  File "./doxypypy.py", line 614, in visit_Module
    self.generic_visit(node, containingNodes=containingNodes)
  File "./doxypypy.py", line 566, in generic_visit
    self.visit(item, containingNodes=kwargs['containingNodes'])
  File "./doxypypy.py", line 582, in visit
    return visitor(node, containingNodes=containingNodes)
  File "./doxypypy.py", line 568, in generic_visit
    self.visit(value, containingNodes=kwargs['containingNodes'])
  File "./doxypypy.py", line 582, in visit
    return visitor(node, containingNodes=containingNodes)
TypeError: visit_Constant() got an unexpected keyword argument 'containingNodes'
```
Looks like the function `visit_Constant()` was just recently added (https://github.com/python/cpython/commit/522a394a72f107ca55701371529b5e4ed20c9fff#diff-2cbfaa4a57fa843e2535720e9adaea77).

**Comment by fer-rum** [comment]
I wonder if this could be triaged by just adding a dummy, that takes the additional argument.

**Comment by svigerske** [comment]
I worked around it by adding
```diff
@@ -765,6 +765,9 @@ class AstWalker(NodeVisitor):
         # Remove the item we pushed onto the containing nodes hierarchy.
         containingNodes.pop()
 
+    def visit_Constant(self, node, **kwargs):
+        super().visit_Constant(node);
+
     def parseLines(self):
         """Form an AST for the code and produce a new version of the source."""
         inAst = parse(''.join(self.lines), self.inFilename)
```
But the other `visit_*` functions do so much more so that I wonder whether calling only the function from the upper class will be sufficient. (I have no idea about the functionality of this code.)

**Comment by fer-rum** [comment]
Thank you for sharing :)

I think it would be worth a pull request and if only to direct attention to the issue and maybe provide a starting point for a complete fix.

**Comment by alexander-dammeier** [comment]
Will the pull request be merged into a new release? We had the same problem in one of our projects.

**Comment by Feneric** [comment]
Generally I try to merge pull requests that don't break existing tests and cover all new functionality with new tests pretty quickly (with the understanding that I typically only get to review things some weeknights and most weekends).

**Comment by alexdewar** [comment]
Hello! I'm still getting this issue. Is there any chance of merging this PR? Would really help me out :smiley:

**Comment by AokiAhishatsu** [comment]
> Hello! I'm still getting this issue. [...]
+1

**Comment by IceTDrinker** [comment]
Is the project still maintaned ? Last update looks ancient

**Comment by Feneric** [comment]
Sure, it's maintained, but it's also pretty stable and already working for a lot of people and I'm hesitant to commit changes that don't have any tests backing them up. It's not my day job and requests can only be serviced when I'm free, and if I have to write tests for changes to it myself I have to commit a lot more time up front.

**Comment by IceTDrinker** [comment]
Sounds fair, existing tests seem to be failing on my computer though (python 3.8). Which version of python are supposed to be supported ?

**Comment by dcdolson** [comment]
For what it's worth, I got this issue the first time I tried doxypypy, on the first module I tried it on. It does not seem like an obscure corner case, rather seems to make this tool unusable.

**Comment by dcdolson** [comment]
This seems to be working better when pulling and building from source. The dockerhub image I was using had an out-of-date version.

**Comment by esaule** [comment]
BTW, I see have a similar issue. I upgraded to debian 11 today and updated doxypypy. I get this error:

```
Traceback (most recent call last):
  File "/home/erik/.local/bin/doxypypy", line 8, in <module>
    sys.exit(main())
  File "/home/erik/.local/lib/python3.9/site-packages/doxypypy/doxypypy.py", line 830, in main
    astWalker.parseLines()
  File "/home/erik/.local/lib/python3.9/site-packages/doxypypy/doxypypy.py", line 743, in parseLines
    self.visit(inAst)
  File "/home/erik/.local/lib/python3.9/site-packages/doxypypy/doxypypy.py", line 569, in visit
    return visitor(node, containingNodes=containingNodes)
  File "/home/erik/.local/lib/python3.9/site-packages/doxypypy/doxypypy.py", line 594, in visit_Module
    self.generic_visit(node, containingNodes=kwargs.get('containingNodes',
  File "/home/erik/.local/lib/python3.9/site-packages/doxypypy/doxypypy.py", line 553, in generic_visit
    self.visit(item, containingNodes=kwargs['containingNodes'])
  File "/home/erik/.local/lib/python3.9/site-packages/doxypypy/doxypypy.py", line 569, in visit
    return visitor(node, containingNodes=containingNodes)
  File "/home/erik/.local/lib/python3.9/site-packages/doxypypy/doxypypy.py", line 735, in visit_ClassDef
    self.generic_visit(node, containingNodes=containingNodes)
  File "/home/erik/.local/lib/python3.9/site-packages/doxypypy/doxypypy.py", line 553, in generic_visit
    self.visit(item, containingNodes=kwargs['containingNodes'])
  File "/home/erik/.local/lib/python3.9/site-packages/doxypypy/doxypypy.py", line 569, in visit
    return visitor(node, containingNodes=containingNodes)
  File "/home/erik/.local/lib/python3.9/site-packages/doxypypy/doxypypy.py", line 555, in generic_visit
    self.visit(value, containingNodes=kwargs['containingNodes'])
  File "/home/erik/.local/lib/python3.9/site-packages/doxypypy/doxypypy.py", line 569, in visit
    return visitor(node, containingNodes=containingNodes)
TypeError: visit_Constant() got an unexpected keyword argument 'containingNodes'
```

**Comment by Feneric** [comment]
All 3.8 problems should now be fixed.
