### ISSUE TITLE
IndexError: list index out of range -- if NOTE: lines are not separated by a blank line.

### ISSUE THREAD

**Issue by dcdolson** [Feneric/doxypypy#78]
I found this could happen if there are two NOTE: or similar keyword on adjacent lines.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/doxypypy-0.8.8.6-py3.9.egg/doxypypy/doxypypy.py", line 927, in <module>
  File "/usr/local/lib/python3.9/site-packages/doxypypy-0.8.8.6-py3.9.egg/doxypypy/doxypypy.py", line 915, in main
  File "/usr/local/lib/python3.9/site-packages/doxypypy-0.8.8.6-py3.9.egg/doxypypy/doxypypy.py", line 796, in parseLines
  File "/usr/local/lib/python3.9/site-packages/doxypypy-0.8.8.6-py3.9.egg/doxypypy/doxypypy.py", line 586, in visit
  File "/usr/local/lib/python3.9/site-packages/doxypypy-0.8.8.6-py3.9.egg/doxypypy/doxypypy.py", line 618, in visit_Module
  File "/usr/local/lib/python3.9/site-packages/doxypypy-0.8.8.6-py3.9.egg/doxypypy/doxypypy.py", line 570, in generic_visit
  File "/usr/local/lib/python3.9/site-packages/doxypypy-0.8.8.6-py3.9.egg/doxypypy/doxypypy.py", line 586, in visit
  File "/usr/local/lib/python3.9/site-packages/doxypypy-0.8.8.6-py3.9.egg/doxypypy/doxypypy.py", line 777, in visit_ClassDef
  File "/usr/local/lib/python3.9/site-packages/doxypypy-0.8.8.6-py3.9.egg/doxypypy/doxypypy.py", line 438, in _processDocstring
  File "/usr/local/lib/python3.9/site-packages/doxypypy-0.8.8.6-py3.9.egg/doxypypy/doxypypy.py", line 216, in __alterDocstring
IndexError: list index out of range
```
E.g., if in a docstring
```
  NOTE: this is a note
  NOTE: this note is on the next line
```
@Feneric this helped me: https://github.com/dcdolson/doxypypy/commit/6071fc63eb13c1c7ced0efbf7912df2df465f2c1

Let me know if you want me to fix it in any way before creating a pull request.

**Comment by dcdolson** [comment]
back-trace looks similar to #40

**Comment by dcdolson** [comment]
I created PR #79 to address this.
